[package]
name = "panoptes-stake-accounts"
description = "Panoptes: Enterprise Security for the Community by the Community"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
version = "1.4.26"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.1"
solana-clap-utils = { path = "../clap-utils", version = "1.4.26" }
solana-cli-config = { path = "../cli-config", version = "1.4.26" }
solana-client = { path = "../client", version = "1.4.26" }
solana-remote-wallet = { path = "../remote-wallet", version = "1.4.26" }
solana-sdk = { path = "../sdk", version = "1.4.26" }
solana-stake-program = { path = "../programs/stake", version = "1.4.26" }

[dev-dependencies]
solana-runtime = { path = "../runtime", version = "1.4.26" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
