[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "panoptes-watchtower"
description = "Panoptes: Enterprise Security for the Community by the Community"
version = "1.4.26"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.1"
log = "0.4.8"
humantime = "2.0.1"
solana-clap-utils = { path = "../clap-utils", version = "1.4.26" }
solana-cli-config = { path = "../cli-config", version = "1.4.26" }
solana-cli-output = { path = "../cli-output", version = "1.4.26" }
solana-client = { path = "../client", version = "1.4.26" }
solana-logger = { path = "../logger", version = "1.4.26" }
solana-metrics = { path = "../metrics", version = "1.4.26" }
solana-notifier = { path = "../notifier", version = "1.4.26" }
solana-sdk = { path = "../sdk", version = "1.4.26" }
solana-version = { path = "../version", version = "1.4.26" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
