[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "I will find you and I will stake you"
edition = "2018"
homepage = "https://solana.com/"
license = "Apache-2.0"
name = "panoptes-stake-o-matic"
repository = "https://github.com/solana-labs/stake-o-matic"
version = "1.4.26"

[dependencies]
clap = "2.33.0"
log = "0.4.8"
serde_yaml = "0.8.13"
solana-clap-utils = { path = "../clap-utils", version = "1.4.26" }
solana-client = { path = "../client", version = "1.4.26" }
solana-cli-config = { path = "../cli-config", version = "1.4.26" }
solana-cli-output = { path = "../cli-output", version = "1.4.26" }
solana-logger = { path = "../logger", version = "1.4.26" }
solana-metrics = { path = "../metrics", version = "1.4.26" }
solana-notifier = { path = "../notifier", version = "1.4.26" }
solana-sdk = { path = "../sdk", version = "1.4.26" }
solana-stake-program = { path = "../programs/stake", version = "1.4.26" }
solana-transaction-status = { path = "../transaction-status", version = "1.4.26" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
