[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-cli-config"
description = "Panoptes: Enterprise Security for the Community by the Community"
version = "1.4.26"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
dirs-next = "2.0.0"
lazy_static = "1.4.0"
serde = "1.0.112"
serde_derive = "1.0.103"
serde_yaml = "0.8.13"
url = "2.1.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
