[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-scripts"
description = "Panoptes: Enterprise Security for the Community by the Community"
version = "1.4.26"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
csv = "1.1"
serde = { version = "1.0.112", features = ["derive"] }

[[bin]]
name = "panoptes-csv-to-validator-infos"
path = "src/csv_to_validator_infos.rs"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
