[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "panoptes-ledger-tool"
description = "Panoptes: Enterprise Security for the Community by the Community"
version = "1.4.26"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
bs58 = "0.3.1"
bytecount = "0.6.0"
clap = "2.33.1"
csv = "1.1.3"
futures = "0.3.5"
futures-util = "0.3.5"
histogram = "*"
itertools = "0.9.0"
log = { version = "0.4.8" }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.56"
serde_yaml = "0.8.13"
solana-clap-utils = { path = "../clap-utils", version = "1.4.26" }
solana-cli-output = { path = "../cli-output", version = "1.4.26" }
solana-ledger = { path = "../ledger", version = "1.4.26" }
solana-logger = { path = "../logger", version = "1.4.26" }
solana-measure = { path = "../measure", version = "1.4.26" }
solana-runtime = { path = "../runtime", version = "1.4.26" }
solana-sdk = { path = "../sdk", version = "1.4.26" }
solana-stake-program = { path = "../programs/stake", version = "1.4.26" }
solana-storage-bigtable = { path = "../storage-bigtable", version = "1.4.26" }
solana-transaction-status = { path = "../transaction-status", version = "1.4.26" }
solana-version = { path = "../version", version = "1.4.26" }
solana-vote-program = { path = "../programs/vote", version = "1.4.26" }
tempfile = "3.1.0"
tokio = { version = "0.2.22", features = ["full"] }

[dev-dependencies]
assert_cmd = "1.0"

[target."cfg(unix)".dependencies]
signal-hook = "0.1.15"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
